remote_theme: chirpy
lang: en
timezone: America/Los_Angeles
plugins:
- jekyll-remote-theme
github:
  username: Lord-of-Bugs

social:
  name: Muchan Li
  email: limuchan28@gmail.com
  links:
    - https://github.com/Lord-of-Bugs

avatar: "./shogun-ringo.jpg"
