remote_theme: abhinavs/moonwalk
plugins:
- jekyll-remote-theme
theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  appearance_toggle: true # if appearance can be switched by user
  date_format: "%Y-%m-%d" # customize how date is formatted
